---
type: showroom
tabs:
  - name: Terminal
    path: '/wetty'
    port: '443'
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
    external: true
  - name: RHDH
    url: 'https://backstage-rhdh-${TEAM_ID}.${DOMAIN}'
    external: true
  - name: ArgoCD (Cluster)
    url: 'https://openshift-gitops-server-openshift-gitops.${DOMAIN}'
    external: true
  - name: ArgoCD (Apps)
    url: 'https://rhdh-gitops-server-rhdh-gitops.${DOMAIN}'
    external: true
