---
type: showroom
tabs:
  - name: Terminal
    path: '/wetty'
    port: '443'
  - name: OCP Console
    url: 'https://console-openshift-console.apps.cluster-rz66n.rz66n.sandbox122.opentlc.com'
    external: true
  - name: RHDH
    url: 'https://backstage-rhdh-team6.apps.cluster-rz66n.rz66n.sandbox122.opentlc.com'
    external: true
