= Module 3: Software Templates and Developer Experience

include::../style.adoc[]

== Overview



Platform Engineers will often be the authors of Templates, and use them to create "*golden paths*" that follow best practices and use approved processes and tooling. Development teams will be the consumers of Templates to create new software and automate their tasks. Using Templates reduces cognitive load on the development teams by allowing them to focus on development tasks, while platform concerns are addressed by the template.

Templates are defined using YAML, but are rendered as a rich form in the {product_name_rhdh} UI when used by development teams.

== Module Objectives

* Create a Template (as the Platform Engineer)
* Register the Template in the Software  (as the Platform  Engineer)
* Create a new Component, GitLab Repository, and GitOps Application from the Template (as a Developer)

== Team Organization

Thanks again to the one who set up the Internal Developer Platform for the team. *Good Guy* !
Now, for the following parts, everyone will lead a part. 
There are 3 different templates to build and import. Difficulties are the same! (Easy)

NOTE: Templates to import have been generated by an AI. We should be careful ;)


